% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Feb-2024 01:25:47
%  MATLAB version: 9.14.0.2337262 (R2023a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

x2024_01_31_03_100Hz = saveVarsMat.x2024_01_31_03_100Hz; % <1x1 table> unsupported class

clear saveVarsMat;
